# -*- mode: ruby -*-
# # vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

$network_address_prefix = '192.168.0'
$public_bridge_name = nil

require 'fileutils'

def config_pxe_client_network(config, mac)
  if $public_bridge_name
    config.vm.network :public_network,
      dev: $public_bridge_name,
      mode: 'bridge',
      type: 'bridge',
      mac: mac,
      ip: "#{$network_address_prefix}.0",
      auto_config: false
  else
    config.vm.network :private_network,
      mac: mac,
      ip: "#{$network_address_prefix}.0",
      auto_config: false
  end
end

Vagrant.configure('2') do |config|
    config.vm.box = 'fedora-coreos'
  
    config.vm.provider :libvirt do |lv, config|
      lv.memory = 256
      lv.cpus = 2
      lv.cpu_mode = 'host-passthrough'
      # lv.nested = true
      lv.keymap = 'de'
    end

    config.vm.define :core do |config|
        config.vm.hostname = 'core.home.molier.net'
        if $public_bridge_name
          config.vm.network :public_network,
            dev: $public_bridge_name,
            mode: 'bridge',
            type: 'bridge',
            mac: '080027000000',
            ip: "#{$network_address_prefix}.2"
        else
          config.vm.network :private_network,
            mac: '080027000000',
            ip: "#{$network_address_prefix}.2",
            libvirt__dhcp_enabled: false,
            libvirt__forward_mode: 'none'
        end
        config.vm.provider :libvirt do |lv, config|
          lv.memory = 1024
          lv.qemuargs :value => '-fw_cfg'
          lv.qemuargs :value => "name=opt/com.coreos/config,file=/tmp/core.ign"
        end
        config.vm.network "forwarded_port", guest: 80, host: 80
        config.vm.network "forwarded_port", guest: 443, host: 443
    end

end
